#!/bin/bash
        export PATH=$PATH:/usr/sbin:/usr/bin
        #Create Directories and files for studetnts
        echo -e  " Creating accounts based on /root/inputfiles/fresherDetails.txt file \n"
        awk '{print$1":"$2}' /root/inputfiles/fresherDetails.txt > /root/inputfiles/cleanfresherDetails.txt
        for student in $(cat /root/inputfiles/cleanstudentDetails.txt)
        do
                Name="$(echo -e  $student | awk -F:  '{print $1}')"
                AppNumber="$(echo -e  $student | awk -F:  '{print $2}')"
                Password="$(echo -e  $Name$AppNumber)"
                echo $Password
#       # Check if student is already exist in System
                grep $RollNumber /etc/passwd
                        if [ $? -eq 0 ]
                        then
                           echo -e  " \n User $Name is already in system"
                        else
                           echo -e  "\n Creating user $Name"
                           mkdir /home/$Name 2>/dev/null
                           useradd -u $AppNumber -m -d /home/$Name -s /bin/bash  $Name 2>/dev/null
                           echo $Password | passwd $NAME
                           chown  "$Name":"$Name" /home/$Name 2>/dev/null
                           cp /root/scripts/studentscripts/* /home/$Name
                           cp /root/scripts/studentscripts/.bashrc /home/$Hostel/$Room/$Name
                           chown  "$Name":"$Name" /home/$Name/* 2>/dev/null
                       fi
        done
